#include "ffc/network_renderer.hpp"

#include <algorithm>
#include <iostream>

namespace ffc {
void NetworkRenderer::show_metadata(const NetworkMetadata& metadata, const std::string& history_path) const { ui_.section("Public network metadata"); ui_.key_value("Observed at", metadata.observed_at_utc.empty() ? "unknown" : metadata.observed_at_utc); ui_.key_value("Public IP", metadata.public_ip_lookup_succeeded ? ui_.accent(metadata.public_ip) : ui_.warning("lookup failed")); ui_.key_value("Default interface", metadata.default_interface.empty() ? "unknown" : metadata.default_interface); ui_.key_value("Default gateway", metadata.default_gateway.empty() ? "unknown" : metadata.default_gateway); ui_.key_value("Connection profile", metadata.connection_profile.empty() ? "unknown" : metadata.connection_profile); if (!metadata.wifi_ssid.empty()) { ui_.key_value("Wi-Fi SSID", metadata.wifi_ssid); ui_.key_value("Wi-Fi BSSID", metadata.wifi_bssid.empty() ? "unknown" : metadata.wifi_bssid); ui_.key_value("Wi-Fi security", metadata.wifi_security.empty() ? "unknown" : metadata.wifi_security); } if (!metadata.country.empty()) ui_.key_value("Country", metadata.country); if (!metadata.timezone.empty()) ui_.key_value("Timezone", metadata.timezone); if (!metadata.isp.empty()) ui_.key_value("ISP", metadata.isp); if (!metadata.autonomous_system.empty()) ui_.key_value("Autonomous system", metadata.autonomous_system); ui_.key_value("History", history_path); if (!metadata.diagnostic.empty()) ui_.key_value("Notice", ui_.warning(metadata.diagnostic)); std::cout << "\n  " << ui_.muted("The public-IP provider received this lookup request.") << '\n'; }
void NetworkRenderer::show_history(const std::vector<std::string>& records, const std::string& history_path) const { ui_.section("Saved public network metadata"); ui_.key_value("History", history_path); if (records.empty()) { std::cout << "  " << ui_.muted("No saved observations.") << '\n'; return; } std::cout << "  " << ui_.muted("timestamp (UTC)  public IP  interface  gateway  profile  SSID  BSSID  security  country  timezone  ISP  ASN  VPN") << '\n'; for (auto record : records) { for (auto& character : record) if (character == '\t') character = ' '; std::cout << "  " << record << '\n'; } }
void NetworkRenderer::show_diagnostics(const NetworkDiagnostics& diagnostics) const { ui_.section("Network reachability probes"); std::cout << "  " << ui_.muted("Two ICMP echo requests are sent to each public resolver.") << '\n'; for (const auto& probe : diagnostics.probes) { const std::string result = !probe.command_available ? ui_.danger("PING UNAVAILABLE") : probe.reachable ? ui_.success("REACHABLE") : ui_.warning("NO REPLY"); std::cout << "  " << result << "  " << ui_.accent(probe.destination) << '\n'; if (!probe.output.empty()) std::cout << "    " << probe.output; if (!probe.output.empty() && probe.output.back() != '\n') std::cout << '\n'; } ui_.section("Traceroute to 1.1.1.1"); std::cout << "  " << ui_.muted("Numeric addresses only; one query per hop; maximum 8 hops.") << '\n'; if (!diagnostics.traceroute_command_available) std::cout << "  " << ui_.danger("traceroute is not installed. Run scripts/setup-firewall-dev.sh to install it.") << '\n'; else if (diagnostics.traceroute_output.empty()) std::cout << "  " << ui_.warning("Traceroute produced no output.") << '\n'; else { std::cout << diagnostics.traceroute_output; if (diagnostics.traceroute_output.back() != '\n') std::cout << '\n'; if (!diagnostics.traceroute_completed) std::cout << "  " << ui_.muted("The route did not complete; timed-out hops are still useful evidence.") << '\n'; } std::cout << "\n  " << ui_.muted("Run only when you intend to generate diagnostic traffic; results do not identify an attacker or network type.") << '\n'; }
void NetworkRenderer::show_security_advisories(const SecurityAdvisoryReport& report) const { ui_.section("Available security advisories"); std::cout << "  " << ui_.muted("Explicit DNF5 query only; no packages, repositories, or firewall settings are changed.") << '\n'; if (!report.dnf_available) { std::cout << "  " << ui_.danger_badge("DNF5 UNAVAILABLE") << " " << ui_.warning(report.diagnostic) << '\n'; return; } if (!report.query_succeeded) { std::string detail = report.diagnostic; for (auto& character : detail) if (static_cast<unsigned char>(character) < 32U || character == '\x7f') character = ' '; if (detail.size() > 240) detail.resize(240); std::cout << "  " << ui_.warning_badge("QUERY FAILED") << " " << ui_.warning(detail) << '\n'; return; } ui_.key_value("Available security advisories", report.advisory_count == 0 ? ui_.success_badge("NONE") : ui_.warning_badge(std::to_string(report.advisory_count))); if (report.cves.empty()) { ui_.key_value("Referenced CVEs", ui_.muted("none reported by available advisories")); return; } constexpr std::size_t cve_limit = 20; std::string cves; for (std::size_t index = 0; index < std::min(report.cves.size(), cve_limit); ++index) cves += (cves.empty() ? "" : ", ") + report.cves[index]; if (report.cves.size() > cve_limit) cves += " … (" + std::to_string(report.cves.size() - cve_limit) + " more)"; ui_.key_value("Referenced CVEs", ui_.warning(cves)); std::cout << "\n  " << ui_.muted("Review the advisory and affected package before updating; a CVE reference is not proof of local exploitability.") << '\n'; }
} // namespace ffc
